import { Global, Module } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import config from '../config/app.config';
import { MongoService } from '../services/mongo.service';
import {
  ActivityLogEvent,
  ActivityLogEventSchema,
  AuthSecurity,
  AuthSecuritySchema,
  AuthUser,
  AuthUserSchema,
  Department,
  DepartmentSchema,
  EmailHistory,
  EmailHistorySchema,
  LoginHistory,
  LoginHistorySchema,
  HrPlan,
  HrPlanSchema,
  TeamMember,
  TeamMemberSchema,
  UserProfile,
  UserProfileSchema,
  LeaveRequest,
  LeaveRequestSchema,
  Project,
  ProjectSchema,
  Whereabouts,
  WhereaboutsSchema,
  DutyOfCare,
  DutyOfCareSchema,
  IncidentReport,
  IncidentReportSchema,
  Vehicle,
  VehicleSchema,
  VehicleLocationHistory,
  VehicleLocationHistorySchema,
  RiskAssessment,
  RiskAssessmentSchema,
  WorkspaceFolder,
  WorkspaceFolderSchema,
  WorkspaceFile,
  WorkspaceFileSchema,
  RateCard,
  RateCardSchema,
  Timesheet,
  TimesheetSchema,
  VehicleCheck,
  VehicleCheckSchema,
} from '../schemas';

@Global()
@Module({
  imports: [
    MongooseModule.forRoot(config.mongodb_uri),
    MongooseModule.forFeature([
      { name: AuthUser.name, schema: AuthUserSchema },
      { name: Department.name, schema: DepartmentSchema },
      { name: AuthSecurity.name, schema: AuthSecuritySchema },
      { name: EmailHistory.name, schema: EmailHistorySchema },
      { name: LoginHistory.name, schema: LoginHistorySchema },
      { name: HrPlan.name, schema: HrPlanSchema },
      { name: TeamMember.name, schema: TeamMemberSchema },
      { name: ActivityLogEvent.name, schema: ActivityLogEventSchema },
      { name: UserProfile.name, schema: UserProfileSchema },
      { name: LeaveRequest.name, schema: LeaveRequestSchema },
      { name: Project.name, schema: ProjectSchema },
      { name: Whereabouts.name, schema: WhereaboutsSchema },
      { name: DutyOfCare.name, schema: DutyOfCareSchema },
      { name: IncidentReport.name, schema: IncidentReportSchema },
      { name: Vehicle.name, schema: VehicleSchema },
      {
        name: VehicleLocationHistory.name,
        schema: VehicleLocationHistorySchema,
      },
      { name: RiskAssessment.name, schema: RiskAssessmentSchema },
      { name: WorkspaceFolder.name, schema: WorkspaceFolderSchema },
      { name: WorkspaceFile.name, schema: WorkspaceFileSchema },
      { name: RateCard.name, schema: RateCardSchema },
      { name: Timesheet.name, schema: TimesheetSchema },
      { name: VehicleCheck.name, schema: VehicleCheckSchema },
    ]),
  ],
  providers: [MongoService],
  exports: [MongoService, MongooseModule],
})
export class MongoModule {}
